<?php

namespace App\Http\Requests\ParameterRequest;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Http\Exceptions\HttpResponseException;
use Illuminate\Contracts\Validation\Validator;
use Illuminate\Http\Request;

class StoreWeekDaysRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules(Request $request)
    {
        return [
            "*.project_id"=>"required|exists:projects,id",
            "*.from"=>"required_if:*.enabled,1",
            "*.to"=>"required_if:*.enabled,1",
            "*.enabled"=>"nullable|boolean",
            "*.order"=>"required|integer",
            "*.title"=>"required|string|min:3|max:255",
        ];
    }

    /**
     * @return array
     */
    public function messages()
    {
        $validation = [];
        $validation["*.from.required_if"] =  "Выберите время";
        $validation["*.to.required_if"] =  "Выберите время";
        return array_merge($validation,parent::messages()); // TODO: Change the autogenerated stub
    }

    /**
     * @param Validator $validator
     */
    public function failedValidation(Validator $validator)
    {
        throw new HttpResponseException(response()->json([
            'errors' => $validator->messages(),
            'errorType'=>'VALIDATION_ERROR'
        ],422));
    }
}
