<?php

namespace App\Http\Requests\ProjectOfficePhonesRequest;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Http\Exceptions\HttpResponseException;
use Illuminate\Contracts\Validation\Validator;
use Illuminate\Http\Request;

class ProjectOfficePhonesRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules(Request $request)
    {
        return [
            "project_id"=>"required|exists:projects,id",
            "phone"=>"required|string|min:3|max:255",
            "extra"=>"nullable|string|min:3|max:255",
        ];
    }

    /**
     * @return array
     */
    public function messages()
    {
        $validation = [];
        $validation["phone.required"] =  "Заполните номер телефона";
        return array_merge($validation,parent::messages()); // TODO: Change the autogenerated stub
    }

    /**
     * @param Validator $validator
     */
    public function failedValidation(Validator $validator)
    {
        throw new HttpResponseException(response()->json([
            'errors' => $validator->messages(),
            'errorType'=>'VALIDATION_ERROR'
        ],422));
    }
}
